--Core
require("core.plugins")
require("core.mappings")
require("core.colorsheme")
require("core.config")

--Config
require("config.treesitter")
require("config.bufferline")
require("config.toggleterm")
require("config.telescope")
require("config.autopairs")
require("config.gitsigns")
require("config.lualine")
require("config.neotree")
require("config.nullls")
require("config.mason")
require("config.lsp")
require("config.cmp")
